import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SystemJSImportMap } from '@/app/components/SystemJSImportMap'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SystemJSImportMap />
        {children}
      </body>
    </html>
  )
}
